services:
  video-analysis-client:
    build: .
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./config:/app/config:ro
      - ../data:/app/data:rw
    restart: unless-stopped